/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dennis
 */

import Calcolatrice.Calcolatrice;
import java.util.HashSet;
import java.util.Set;
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Casella = new javax.swing.JTextField();
        bottone7 = new javax.swing.JButton();
        bottone8 = new javax.swing.JButton();
        bottone9 = new javax.swing.JButton();
        bottone4 = new javax.swing.JButton();
        bottone5 = new javax.swing.JButton();
        bottone6 = new javax.swing.JButton();
        bottone3 = new javax.swing.JButton();
        bottone2 = new javax.swing.JButton();
        bottone1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        somma = new javax.swing.JButton();
        sottrazza = new javax.swing.JButton();
        moltiplicazione = new javax.swing.JButton();
        divisione = new javax.swing.JButton();
        uguale = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        Bottone0 = new javax.swing.JButton();
        BottonePunto = new javax.swing.JButton();
        BottonePercentage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bottone7.setText("7");
        bottone7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottone7MouseClicked(evt);
            }
        });
        bottone7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bottone7KeyPressed(evt);
            }
        });

        bottone8.setText("8");
        bottone8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottone8MouseClicked(evt);
            }
        });
        bottone8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottone8ActionPerformed(evt);
            }
        });
        bottone8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bottone8KeyPressed(evt);
            }
        });

        bottone9.setText("9");
        bottone9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottone9MouseClicked(evt);
            }
        });
        bottone9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bottone9KeyPressed(evt);
            }
        });

        bottone4.setText("4");
        bottone4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottone4MouseClicked(evt);
            }
        });
        bottone4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bottone4KeyPressed(evt);
            }
        });

        bottone5.setText("5");
        bottone5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottone5MouseClicked(evt);
            }
        });
        bottone5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottone5ActionPerformed(evt);
            }
        });

        bottone6.setText("6");
        bottone6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottone6MouseClicked(evt);
            }
        });
        bottone6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottone6ActionPerformed(evt);
            }
        });

        bottone3.setActionCommand("1");
        bottone3.setLabel("3");
        bottone3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottone3MouseClicked(evt);
            }
        });

        bottone2.setLabel("2");
        bottone2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottone2MouseClicked(evt);
            }
        });

        bottone1.setLabel("1");
        bottone1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottone1MouseClicked(evt);
            }
        });

        jLabel1.setText("Calcolatrice");

        somma.setText("+");
        somma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sommaMouseClicked(evt);
            }
        });
        somma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sommaActionPerformed(evt);
            }
        });

        sottrazza.setText("-");
        sottrazza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sottrazzaMouseClicked(evt);
            }
        });

        moltiplicazione.setText("*");
        moltiplicazione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moltiplicazioneMouseClicked(evt);
            }
        });

        divisione.setText("/");
        divisione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisioneMouseClicked(evt);
            }
        });

        uguale.setText("=");
        uguale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ugualeMouseClicked(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearButtonMouseClicked(evt);
            }
        });
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        Bottone0.setText("0");
        Bottone0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bottone0MouseClicked(evt);
            }
        });

        BottonePunto.setText(".");
        BottonePunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BottonePuntoMouseClicked(evt);
            }
        });

        BottonePercentage.setText("%");
        BottonePercentage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BottonePercentageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uguale, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Bottone0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bottone4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bottone7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bottone3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bottone5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bottone8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bottone2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bottone9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(somma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(bottone6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bottone1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(moltiplicazione, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sottrazza, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BottonePunto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BottonePercentage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(divisione, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Casella, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearButton)
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Casella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottone7)
                    .addComponent(bottone8)
                    .addComponent(bottone9)
                    .addComponent(somma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottone4)
                    .addComponent(bottone5)
                    .addComponent(bottone6)
                    .addComponent(sottrazza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottone3)
                    .addComponent(bottone2)
                    .addComponent(moltiplicazione)
                    .addComponent(bottone1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divisione)
                    .addComponent(Bottone0)
                    .addComponent(BottonePunto)
                    .addComponent(BottonePercentage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(uguale)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Calcolatrice calcolatrice = new Calcolatrice();
    private void bottone8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottone8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottone8ActionPerformed

    private void bottone5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottone5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottone5ActionPerformed

    private void bottone6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottone6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottone6ActionPerformed

    private void sommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sommaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sommaActionPerformed

    private void bottone7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bottone7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottone7KeyPressed

    private void bottone7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottone7MouseClicked
       Casella.setText(Casella.getText()+'7');
    }//GEN-LAST:event_bottone7MouseClicked

    private void bottone8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bottone8KeyPressed
        Casella.setText(Casella.getText()+'8');
    }//GEN-LAST:event_bottone8KeyPressed

    private void bottone9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bottone9KeyPressed
       Casella.setText(Casella.getText()+'9');
    }//GEN-LAST:event_bottone9KeyPressed

    private void bottone4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bottone4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottone4KeyPressed

    private void bottone4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottone4MouseClicked
        Casella.setText(Casella.getText()+'4');
    }//GEN-LAST:event_bottone4MouseClicked

    private void bottone5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottone5MouseClicked
        Casella.setText(Casella.getText()+'5');
    }//GEN-LAST:event_bottone5MouseClicked

    private void bottone6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottone6MouseClicked
        Casella.setText(Casella.getText()+'6');
    }//GEN-LAST:event_bottone6MouseClicked

    private void bottone3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottone3MouseClicked
       Casella.setText(Casella.getText()+'3');
    }//GEN-LAST:event_bottone3MouseClicked

    private void bottone2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottone2MouseClicked
       Casella.setText(Casella.getText()+'2');
    }//GEN-LAST:event_bottone2MouseClicked

    private void bottone1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottone1MouseClicked
       Casella.setText(Casella.getText()+'1');
    }//GEN-LAST:event_bottone1MouseClicked

    private void bottone8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottone8MouseClicked
       Casella.setText(Casella.getText()+'8');
    }//GEN-LAST:event_bottone8MouseClicked

    private void bottone9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottone9MouseClicked
       Casella.setText(Casella.getText()+'9');
    }//GEN-LAST:event_bottone9MouseClicked

    private void sommaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sommaMouseClicked
        calcolatrice.setNum1('+', Float.parseFloat(Casella.getText()));
        Casella.setText("");
    }//GEN-LAST:event_sommaMouseClicked

    private void sottrazzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sottrazzaMouseClicked
        calcolatrice.setNum1('-', Float.parseFloat(Casella.getText()));
        Casella.setText("");
    }//GEN-LAST:event_sottrazzaMouseClicked

    private void moltiplicazioneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moltiplicazioneMouseClicked
        calcolatrice.setNum1('*', Float.parseFloat(Casella.getText()));
        Casella.setText("");
    }//GEN-LAST:event_moltiplicazioneMouseClicked

    private void divisioneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisioneMouseClicked
        calcolatrice.setNum1('/', Float.parseFloat(Casella.getText()));
        Casella.setText("");
    }//GEN-LAST:event_divisioneMouseClicked

    private void ugualeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ugualeMouseClicked
        Float risultato;
        calcolatrice.setNum2(Float.parseFloat(Casella.getText()));
        
        
        risultato = calcolatrice.getResult();
        Casella.setText(risultato.toString());
    }//GEN-LAST:event_ugualeMouseClicked

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void ClearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButtonMouseClicked
        Casella.setText("");
    }//GEN-LAST:event_ClearButtonMouseClicked

    private void Bottone0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bottone0MouseClicked
         Casella.setText(Casella.getText()+'0');
    }//GEN-LAST:event_Bottone0MouseClicked

    private void BottonePuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BottonePuntoMouseClicked
         Casella.setText(Casella.getText()+'.');
    }//GEN-LAST:event_BottonePuntoMouseClicked

    private void BottonePercentageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BottonePercentageMouseClicked
        Casella.setText(calcolatrice.percetage().toString());
    }//GEN-LAST:event_BottonePercentageMouseClicked
                          
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone0;
    private javax.swing.JButton BottonePercentage;
    private javax.swing.JButton BottonePunto;
    private javax.swing.JTextField Casella;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton bottone1;
    private javax.swing.JButton bottone2;
    private javax.swing.JButton bottone3;
    private javax.swing.JButton bottone4;
    private javax.swing.JButton bottone5;
    private javax.swing.JButton bottone6;
    private javax.swing.JButton bottone7;
    private javax.swing.JButton bottone8;
    private javax.swing.JButton bottone9;
    private javax.swing.JButton divisione;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton moltiplicazione;
    private javax.swing.JButton somma;
    private javax.swing.JButton sottrazza;
    private javax.swing.JButton uguale;
    // End of variables declaration//GEN-END:variables
}
